version: "3.6"
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
